// <auto-generated />
namespace SSMS.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Produduct_DropDown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Produduct_DropDown));
        
        string IMigrationMetadata.Id
        {
            get { return "201904221046219_Produduct_DropDown"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
